### PR TITLE
fix: JSON resource type value completion formatted as key

### LINKED ISSUE #450: [Bug]: Resource type completions are not displayed in JSON
### Describe the bug

Expected resource type completions are not displayed by editors (observed in VS Code and Zed) in JSON CloudFormation templates. This seems to be because the returned range for each completion (specifically `textEdit.range.end.character`) is longer than expected and is rejected by the editors.

### Steps to reproduce

1. Create a basic JSON CloudFormation template with an empty resource entry:

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "MyTestResource": {
    }
  }
}
```

2. Trigger a resource type completion:

```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "MyTestResource": {
      "Type": "
    }
  }
}
```

3. No completions are suggested

### Expected behavior

Completions are suggested with available resources (`AWS::ACMPCA::Certificate` etc.)

### CloudFormation template (if applicable)

```yaml
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "MyTestResource": {
      "Type": ""
    }
  }
}
```

### Language Server version

1.4.0

### Editor/IDE

VSCode 1.109.5, Zed 0.224.11

### Operating System

macOS

### Node.js version

v24.13.0

### Logs

```text
This is from Zed's logs, no relevant logs from the language server itself:


INFO  [project::lsp_command] completion out of expected range, start: PointUtf16 { row: 14, column: 8 }, end: PointUtf16 { row: 14, column: 8 }, range: Unclipped(PointUtf16 { row: 14, column: 8 })..Unclipped(PointUtf16 { row: 14, column: 9 })
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kddejong**
CompletionFormatter.formatForJson treated all completions as key insertions — wrapping in quotes with trailing colon and replacing from column 0. This broke resource type value completion in JSON (e.g. typing AWS::S3::B inside "Type": "") because:

1. newText was '"AWS::S3::Bucket":' (colon appended to value)
2. textEdit range started at column 0, wiping out the "Type" key
3. filterText was '"AWS::S3::Bu"' which VS Code couldn't match

Fix: detect value completions (nodeType=string, isValue && !isKey) and replace only the quoted value token with the correct text.

Also fixes debug_tree.ts crash on undefined cfnFileType.

Adds e2e and unit tests for JSON resource type value completion.

fixes #450 

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/autocomplete/CompletionFormatter.ts [hunk 1]
```diff
@@ -95,7 +95,10 @@ export class CompletionFormatter {
 
         // Set filterText for ALL items (including snippets) when in JSON with quotes
         const isInJsonString = documentType === DocumentType.JSON && context.syntaxNode.type === 'string';
-        if (isInJsonString) {
+        const isJsonValueCompletion = documentType === DocumentType.JSON && item.kind === CompletionItemKind.Class;
```
Comment (Zee2413) [inline src/autocomplete/CompletionFormatter.ts]: Same comment as below. Is there information in syntax tree / path that can help figure distinguish key / value better than using `item.kind`? I recall we got recall sophisticated in YAML for key/value. Can anything similar be done in JSON?

**Review by Zee2413 — APPROVED** [review]

**Review by gemammercado — APPROVED** [review]
